"""CLI script for ingesting a knowledge item into BeeHaive.

Usage:
    # Preview mode (default — shows proposed mappings without persisting):
    python backend/scripts/ingest_item.py \
        --url "https://example.com/paper" \
        --title "Paper Title" \
        --type paper

    # Commit mode (persists to Neo4j + LightRAG):
    python backend/scripts/ingest_item.py \
        --url "https://example.com/paper" \
        --title "Paper Title" \
        --type paper \
        --commit

    # Via Makefile:
    make ingest-item URL="..." TITLE="..." TYPE=paper
    make ingest-item URL="..." TITLE="..." TYPE=paper COMMIT=1
"""

import argparse
import logging
import sys

from app.graph.connection import get_session
from app.ingestion.pipeline import ingest
from app.models.ingestion import IngestionSource


def _setup_logging(verbose: bool) -> None:
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(levelname)-8s %(name)s: %(message)s",
    )
    # Quiet noisy libraries
    logging.getLogger("httpx").setLevel(logging.WARNING)
    logging.getLogger("neo4j").setLevel(logging.WARNING)
    logging.getLogger("openai").setLevel(logging.WARNING)


def _format_mappings(mappings) -> str:
    """Format taxonomy mappings for terminal display."""
    if not mappings:
        return "  (geen mappings)"

    lines = []
    # Group by entity type
    by_type = {}
    for m in mappings:
        by_type.setdefault(m.entity_type, []).append(m)

    type_order = ["BuildingBlock", "Guardrail", "Topic", "Author"]
    type_emoji = {
        "BuildingBlock": "[BB]",
        "Guardrail": "[GR]",
        "Topic": "[TP]",
        "Author": "[AU]",
    }

    for entity_type in type_order:
        group = by_type.get(entity_type, [])
        if not group:
            continue
        for m in sorted(group, key=lambda x: -x.confidence):
            prefix = type_emoji.get(entity_type, "    ")
            lines.append(
                f"  {prefix} {m.matched_name} (confidence: {m.confidence:.2f})"
            )

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Ingest a knowledge item into BeeHaive",
    )
    parser.add_argument("--url", required=True, help="Source URL (HTTPS)")
    parser.add_argument("--title", required=True, help="Item title")
    parser.add_argument(
        "--type",
        required=True,
        choices=["paper", "regulation", "guideline", "best_practice"],
        help="Source type",
    )
    parser.add_argument(
        "--commit",
        action="store_true",
        help="Persist to graph (default: dry-run/preview)",
    )
    parser.add_argument(
        "--skip-rag",
        action="store_true",
        help="Skip LightRAG ingest (only write to knowledge graph)",
    )
    parser.add_argument(
        "--summary-nl",
        help="Override NL-summary (otherwise generated by Gemini)",
    )
    parser.add_argument(
        "--curation-score",
        type=int,
        help="Editorial score 0-10 (default: 0 for new items, preserved on re-ingest)",
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="Debug logging")

    args = parser.parse_args()
    _setup_logging(args.verbose)

    source = IngestionSource(
        url=args.url,
        title=args.title,
        source_type=args.type,
        summary_nl=args.summary_nl,
        curation_score=args.curation_score,
    )

    dry_run = not args.commit
    mode = "PREVIEW" if dry_run else "COMMIT"
    print(f"\n{'='*60}")
    print(f"BeeHaive Ingestion — {mode}")
    print(f"{'='*60}")
    print(f"  URL:   {source.url}")
    print(f"  Title: {source.title}")
    print(f"  Type:  {source.source_type}")
    print(f"{'='*60}\n")

    try:
        with get_session() as session:
            result = ingest(
                source=source,
                neo4j_session=session,
                dry_run=dry_run,
                skip_rag=args.skip_rag,
            )
    except ValueError as e:
        print(f"CONFIGURATIEFOUT: {e}")
        sys.exit(1)
    except Exception as e:
        logging.getLogger(__name__).exception("Onverwachte fout")
        print(f"FOUT: {e}")
        sys.exit(1)

    # Display result
    status_display = {
        "preview": "PREVIEW — voorgestelde mappings:",
        "ingested": "INGESTED — item opgeslagen in knowledge graph",
        "duplicate": f"DUPLICATE — item bestaat al: '{result.existing}'",
        "no_mappings_found": "NO MAPPINGS — geen taxonomie-mappings gevonden",
        "fetch_failed": f"FAILED — {result.error}",
        "pii_scan_failed": f"FAILED — {result.error}",
        "engine_unavailable": f"UNAVAILABLE — {result.error}",
        "entity_validation_failed": f"VALIDATION FAILED — {result.error}",
    }

    print(f"Status: {status_display.get(result.status, result.status)}")

    if result.mappings:
        print(f"\nMappings ({len(result.mappings)}):")
        print(_format_mappings(result.mappings))

    if result.status == "ingested" and not result.rag_synced:
        print("\n  ⚠ LightRAG ingest mislukt — item is NIET vindbaar via RAG queries.")

    if result.status == "preview":
        print("\nHerrun met --commit om op te slaan.")

    if result.suggestion:
        print(f"\nSuggestie: {result.suggestion}")

    print()

    # Exit code
    success_statuses = {"preview", "ingested"}
    sys.exit(0 if result.status in success_statuses else 1)


if __name__ == "__main__":
    main()
